services:
  snapcast:
    image: docker.io/sweisgerber/snapcast:latest
    hostname: snapcast
    environment:
      - PUID=1000
      - PGID=1000 # set to audio group ID
      - TZ=Europe/Berlin
      - START_SNAPCLIENT=false # set to `true` for snapclient to start
      # --host: name or ip of compose service or dockerhost
      # --soundcard: <ID> from `snapclient -l` from inside the container
      # - SNAPCLIENT_OPTS=--host snapcast --soundcard <ID>
      #   => Don't use quotes for SNAPCLIENT_OPTS="" !
      # - HOST_AUDIO_GROUP=<AUDIO-GID> # set to GID of host audio group
      - START_AIRPLAY=false # set to 'true' to enable Airplay support via Shairport-sync
    restart: "unless-stopped"
    network_mode: host
# in network mode host port mapping is not required
#    ports:
#      - 1704:1704 # port for the actual audio streaming
#      - 1705:1705 # port for TCP Json RPC
#      - 1780:1780 # port for the SnapWeb Webinterface
    # devices:
      # - /dev/snd:/dev/snd # optional, only if you want to use snapclient
    volumes:
      - /<path>/<to>/<snapcast>/config/:/config/
      - /<path>/<to>/<snapcast>/data/:/data/
      # /audio should get used to place FIFOs for audio playback from mpd/mopidy/host/etc
      - /<path>/<to>/audio-fifos/:/audio/
      # Map to host avahi/dbus service to allow spotify and airplay advertising
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
