#!/usr/bin/with-contenv bash

if [ "$START_SNAPCLIENT" = 'true' ]; then

  exec \
    s6-setuidgid abc /usr/bin/snapclient $SNAPCLIENT_OPTS
else
  exec \
    s6-setuidgid abc echo "Not starting snapclient. Set 'START_SNAPCLIENT=true' to start it."
fi
