#!/usr/bin/with-contenv bash

if [ "$START_AVAHI" = 'true' ]; then
  exec s6-notifyoncheck -d -n 300 -w 1000 -c "dbus-send --system / org.freedesktop.Avahi.Server.GetState" \
    avahi-daemon --no-chroot
fi
