#!/usr/bin/with-contenv bash

if [ "$START_AIRPLAY" = 'true' ]; then
  mkdir -p /run/dbus
  exec s6-notifyoncheck -d -n 300 -w 1000 -c "dbus-send --system / org.freedesktop.DBus.Peer.Ping" \
    dbus-daemon --system --nofork --nopidfile
fi
