#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
    /config \
    /data \
    /audio

# copy config unless it exists
cp -n /defaults/snapserver.conf /config/snapserver.conf

# permissions
lsiown -R abc:abc \
    /config \
    /data \
    /audio

if [ "$START_SNAPCLIENT" = 'true' ]; then
  if [ -n ${HOST_AUDIO_GROUP+x} ]; then
    echo "Add HOST_AUDIO_GROUP: '$HOST_AUDIO_GROUP'"
    addgroup host-audio -g $HOST_AUDIO_GROUP
    addgroup abc host-audio
  fi
else
  echo "Not starting snapclient. Set 'START_SNAPCLIENT=true' to start it."
fi

if [ "$START_AIRPLAY" = 'true' ]; then
  echo "Starting DBUS to enable Airplay"
else
  echo "Not starting DBUS. Set 'START_AIRPLAY=true' to start it and enable Airplay support."
fi

if [ "$START_AVAHI" = 'true' ]; then
  echo "Starting Avahi for Airplay"
else
  echo "Not starting Avahi. Set 'START_AVAHI=true' to start it and enable Avahi support."
fi
