#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
    /config \
    /data \
    /audio

# copy config unless it exists
cp -n /defaults/snapserver.conf /config/snapserver.conf

# permissions
lsiown -R abc:abc \
    /config \
    /data \
    /audio

if [ -n ${HOST_AUDIO_GROUP+x} ]; then
  echo "Add HOST_AUDIO_GROUP: $HOST_AUDIO_GROUP"
  addgroup host-audio -g $HOST_AUDIO_GROUP
  addgroup abc host-audio
fi
